version: '0'

#Ставим и запускаем Portainer
docker volume create portainer_data
docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:2.11.1

services:
  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - ${NS_MONGO_DATA_DIR:-./mongo-data}:/data/db:cached

  nightscout:
    image: nightscout/cgm-remote-monitor:latest
    container_name: nightscout1
    restart: always
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      INSECURE_USE_HTTP: 'true'
      MONGO_CONNECTION: mongodb://mongo:27017/nightscout
      API_SECRET: qwertyuiopas
      CUSTOM_TITLE: CGM_USER
          
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencryp
