version: '3'

services:
  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - ${NS_MONGO_DATA_DIR:-./mongo-data}:/data/db:cached

  nightscout:
    image: nightscout/cgm-remote-monitor:latest
    container_name: nightscout
    restart: always
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      TZ: Europe/Moscow
      INSECURE_USE_HTTP: 'true'
      MONGO_CONNECTION: mongodb://mongo:27017/nightscout
      API_SECRET: qwertyuiopas
      CUSTOM_TITLE: User_CGM
      THEME: colors
      BG_HIGH: 13
      BG_TARGET_TOP: 9
      BG_TARGET_BOTTOM: 4.3
      BG_LOW: 4.0
      SHOW_FORECAST: loop
      SHOW_PLUGINS: openaps pump cob iob sage cage careportal maker
      BASAL_RENDER: icicle
      ENABLE: careportal openaps iob bwp cage basal pump bridge cob loop basal sage override maker alice
      AUTH_DEFAULT_ROLES: denied

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencryp
